--- 
- hosts: all
  become: yes
  user: ubuntu
  tasks:
    - name: Adiciona repositório do PostgreSQL
      apt_repository:
       filename: pgdg.list
       repo: deb http://apt.postgresql.org/pub/repos/apt xenial-pgdg main
       state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

