--- 
- hosts: all
  become: yes
  user: ubuntu
  tasks:
    - name: Adiciona repositório do PostgreSQL
      shell: echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      args:
       executable: /bin/bash
       